import React from "react";
import Navbar from "@/components/nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <>
          <Navbar />
        </>
        <div className="flex  w-full h-full">
          <div className="w-1/3 pt-10" >
            <Sidebar />
          </div>
          <div className="w-full" >
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
